### PR TITLE
perf: improve perf and fix benchmarks

### LINKED ISSUE #55: Without observables key it doesn't work

### PR DESCRIPTION
**Pull request by neoziro**
Closes #55

### CODE REVIEW

**Comment by matthieuprat** [comment]
Nice work!

File: src/utils/createHOCFromMapper.js [hunk 1]
```diff
@@ -21,14 +21,20 @@ const createComponentFromMappers = (mappers, childFactory) => {
...
 
       this.childPropsSubscription = obsConfig.toESObservable(childProps$).subscribe({
-        next: childProps => this.setState({ childProps }),
+        next: (childProps) => {
+          if (!this.state && !this.mounted) {
+            this.state = { childProps }
+          } else {
+            this.setState({ childProps })
+          }
+        },
```
Comment (neoziro) [inline src/utils/createHOCFromMapper.js]: Yes a little.
